"""add generation deliveries

Revision ID: 03592778fdee
Revises: 2e1bb167413b
Create Date: 2026-08-23 21:14:10.087646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03592778fdee"
down_revision: str | Sequence[str] | None = "2e1bb167413b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("generation_job_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("recipient_email", sa.String(length=320), nullable=False),
        sa.Column("odoo_partner_id", sa.Integer(), nullable=True),
        sa.Column("odoo_mail_id", sa.Integer(), nullable=True),
        sa.Column("partner_created", sa.Boolean(), nullable=False),
        sa.Column("attachment_count", sa.Integer(), nullable=False),
        sa.Column(
            "sent_artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["generation_job_id"], ["generation_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_deliveries_generation_job_id"),
        "generation_deliveries",
        ["generation_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_deliveries_status"),
        "generation_deliveries",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_generation_deliveries_status"), table_name="generation_deliveries"
    )
    op.drop_index(
        op.f("ix_generation_deliveries_generation_job_id"),
        table_name="generation_deliveries",
    )
    op.drop_table("generation_deliveries")
    # ### end Alembic commands ###
