"""add customer contact fields to project cases

Revision ID: 2e1bb167413b
Revises: 9f7320040539
Create Date: 2026-08-23 17:06:24.233876

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e1bb167413b"
down_revision: str | Sequence[str] | None = "9f7320040539"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_cases",
        sa.Column("customer_email", sa.String(length=320), nullable=True),
    )
    op.add_column(
        "project_cases",
        sa.Column("customer_phone", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_cases", "customer_phone")
    op.drop_column("project_cases", "customer_email")
    # ### end Alembic commands ###
