"""add case photos and visit notes

Revision ID: 3c4ab0fa3877
Revises: 5a080ee8f0e6
Create Date: 2026-08-13 00:32:36.305167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4ab0fa3877'
down_revision: Union[str, Sequence[str], None] = '5a080ee8f0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('window_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['project_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['window_id'], ['case_windows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_case_photos_case_id'), 'case_photos', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_photos_window_id'), 'case_photos', ['window_id'], unique=False)
    op.add_column('project_cases', sa.Column('visit_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_cases', 'visit_notes')
    op.drop_index(op.f('ix_case_photos_window_id'), table_name='case_photos')
    op.drop_index(op.f('ix_case_photos_case_id'), table_name='case_photos')
    op.drop_table('case_photos')
    # ### end Alembic commands ###
