"""create project cases

Revision ID: 5a080ee8f0e6
Revises: 
Create Date: 2026-08-13 00:16:43.734228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a080ee8f0e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prefweb_number', sa.BigInteger(), nullable=False),
    sa.Column('prefweb_version', sa.Integer(), nullable=False),
    sa.Column('alias_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefweb_number', 'prefweb_version', name='uq_project_case_prefweb_document')
    )
    op.create_table('case_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('prefweb_item_id', sa.String(length=100), nullable=False),
    sa.Column('prefweb_id_pos', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=255), nullable=True),
    sa.Column('problem_type', sa.String(length=50), nullable=True),
    sa.Column('commercial_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['project_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'prefweb_item_id', name='uq_case_window_prefweb_item')
    )
    op.create_index(op.f('ix_case_windows_case_id'), 'case_windows', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_windows_case_id'), table_name='case_windows')
    op.drop_table('case_windows')
    op.drop_table('project_cases')
    # ### end Alembic commands ###
