"""add reference photo library

Revision ID: 9e7a840167d1
Revises: f97cfb87b4df
Create Date: 2026-08-13 02:47:14.626879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7a840167d1'
down_revision: Union[str, Sequence[str], None] = 'f97cfb87b4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('room_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('window_type_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_reference_photos_active'), 'reference_photos', ['active'], unique=False)
    op.create_table('case_reference_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('reference_photo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['project_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_photo_id'], ['reference_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'slot', name='uq_case_reference_selection_slot')
    )
    op.create_index(op.f('ix_case_reference_selections_case_id'), 'case_reference_selections', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_reference_selections_reference_photo_id'), 'case_reference_selections', ['reference_photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_reference_selections_reference_photo_id'), table_name='case_reference_selections')
    op.drop_index(op.f('ix_case_reference_selections_case_id'), table_name='case_reference_selections')
    op.drop_table('case_reference_selections')
    op.drop_index(op.f('ix_reference_photos_active'), table_name='reference_photos')
    op.drop_table('reference_photos')
    # ### end Alembic commands ###
