"""drop generation artifact kind uniqueness

Revision ID: 9f7320040539
Revises: 2f57a6fa745d
Create Date: 2026-08-23 13:55:35.609681

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f7320040539"
down_revision: str | Sequence[str] | None = "2f57a6fa745d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_generation_artifact_job_kind"), "generation_artifacts", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_generation_artifact_job_kind"),
        "generation_artifacts",
        ["generation_job_id", "kind"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
