"""add generation artifacts

Revision ID: c731f57aa8df
Revises: 9e7a840167d1
Create Date: 2026-08-21 13:59:22.574319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c731f57aa8df'
down_revision: Union[str, Sequence[str], None] = '9e7a840167d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_job_id', 'kind', name='uq_generation_artifact_job_kind')
    )
    op.create_index(op.f('ix_generation_artifacts_generation_job_id'), 'generation_artifacts', ['generation_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_artifacts_generation_job_id'), table_name='generation_artifacts')
    op.drop_table('generation_artifacts')
    # ### end Alembic commands ###
